#! /bin/bash

LIVE=live/2011
TEST=test

files=$(cd ${TEST} ; ls *.ics | egrep -v 'all-in-one.ics|tournaments.ics')

for file in ${files} ; do
	if [ -f ${LIVE}/${file} ] ; then
		if ! diff -q ${LIVE}/${file} ${TEST}/${file} > /dev/null ; then
			echo "========== diff -Naur ${LIVE}/${file} ${TEST}/${file} =========="
			# sdiff ${LIVE}/${file} ${TEST}/${file}
			ics_diff ${LIVE}/${file} ${TEST}/${file}
		fi
	fi
done

exit 0
